name: Multi-Platform Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Így ha az egyik OS elbukik, a többi még végigfut
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TerminalJack-${{ matrix.os }}
        # Ez a rész a legfontosabb: a '|' jel után jönnek a minták
        path: |
          build/TerminalJack
          build/TerminalJack.exe
          build/**/TerminalJack
          build/**/TerminalJack.exe
        if-no-files-found: error
